### PR TITLE
Seed database

### PR DESCRIPTION
**Pull request by cheyennenoel**

### CODE REVIEW

**Comment by tonykijak** [comment]
Have you considered regular functions over arrow functions outside the context of callbacks?
database/aggregate: do you have a linter?
database/connect: you may not need to explicitly connect, because connection is implicit with your query.
database/seed: Please review line 64; should resolve be invoked? Re: line 68, '.then' is called on an undefined return value. Can the stream.end() be called within the previous '.then', i.e. line 65?

**Comment by cheyennenoel** [comment]
- I'm using the Airbnb style guide with my linter; it prefers arrow functions. Can you give me a line # where you'd prefer a non-arrow function, and I'll see if my linter allows it? Thanks!
- Linted the file; apologies for the typos. Currently only one flag where it doesn't realize the returned promise is multi-line
- Good catch! Was replicating Express docs (https://expressjs.com/en/guide/database-integration.html#mysql) syntax, but looks like it works w/o db.connect()
- Good call! Fixed

**Comment by tonykijak** [comment]
@cheyennenoel Does it give you any issue on line 8 of database/aggregate.js if you use function over arrow?
The rest looks great!

**Comment by cheyennenoel** [comment]
It gives me an "Unexpected unnamed function. (func-names) lint error" if I change line 8 as requested.

If I leave it as an arrow function, it still complains about because it thinks it's a single line function: "[eslint] Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`. (arrow-body-style)"

If I fix as in the commit just now, the linter is happy! Look good?

**Comment by tonykijak** [comment]
Looks great!

**Pull request merged**
